pam_wheel: if getlogin fails fallback to PAM_RUSER
linux-pam/linux-pam pull request #262
Opened 2020-08-26 13:40 UTC by ikerexxe

modules/pam_wheel/pam_wheel.c: if getlogin fails to obtain the real user
ID, then try with PAM_RUSER. Besides, improve indentation.
modules/pam_wheel/pam_wheel.8.xml: indicate that use_uid option uses the
real uid of the calling process.

Resolves:
https://bugzilla.redhat.com/show_bug.cgi?id=1866866

2020-08-26 15:32 UTC, t8m reviewed
Looks good but if you're already changing the indentation on the lines with if(), please also change the condition for NULL/non-NULL pointer values to explicit `== NULL` or `!= NULL`.

2020-08-26 15:32 UTC, t8m commented on modules/pam_wheel/pam_wheel.c
> +        if(!fromsu) {
Please space after if.

2020-08-27 07:20 UTC, ikerexxe commented
> Looks good but if you're already changing the indentation on the lines with if(), please also change the condition for NULL/non-NULL pointer values to explicit `== NULL` or `!= NULL`.

Updated with your comments.

2020-08-27 09:37 UTC, ldv-alt commented
On Wed, Aug 26, 2020 at 06:40:18AM -0700, Iker Pedrosa wrote:
> modules/pam_wheel/pam_wheel.c: if getlogin fails to obtain the real user
> ID, then try with PAM_RUSER. Besides, improve indentation.
> 
> Resolves:
> https://bugzilla.redhat.com/show_bug.cgi?id=1866866

What's the rationale for this change?  The bugzilla bug is not accessible.

Can PAM_RUSER be trusted at all?
Also, is PAM_RUSER valid for the purposes of this module if PAM_RHOST is also set?

2020-08-27 09:48 UTC, ikerexxe commented
> On Wed, Aug 26, 2020 at 06:40:18AM -0700, Iker Pedrosa wrote: modules/pam_wheel/pam_wheel.c: if getlogin fails to obtain the real user ID, then try with PAM_RUSER. Besides, improve indentation. Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=1866866
> What's the rationale for this change? The bugzilla bug is not accessible. Can PAM_RUSER be trusted at all? Also, is PAM_RUSER valid for the purposes of this module if PAM_RHOST is also set?

Sorry, I didn't notice that it was set as private. Now, it's been changed and you should be able to see it.

2020-08-27 09:51 UTC, t8m commented
> What's the rationale for this change? The bugzilla bug is not accessible.

I've opened up the bug. The problem is that currently the terminal windows no longer provide a login session of their own.

> Can PAM_RUSER be trusted at all? Also, is PAM_RUSER valid for the purposes of this module if PAM_RHOST is also set?

Not sure if anything sets PAM_RUSER along with PAM_RHOST - at least I would not expect it to be set. But yeah, perhaps as a safety measure we should use PAM_RUSER only if PAM_RHOST is not set. As for trusting the PAM_RUSER - I do not see a reason why we should not trust it. If a PAM application is setting PAM_RUSER randomly, it is a bug (and security issue) in the application, not in PAM.

2020-08-27 10:26 UTC, ldv-alt commented
On Thu, Aug 27, 2020 at 02:51:22AM -0700, Tomáš Mráz wrote:
> > What's the rationale for this change? The bugzilla bug is not accessible.
> 
> I've opened up the bug. The problem is that currently the terminal windows no longer provide a login session of their own.

Have these terminal emulators stopped using libutempter?
I wonder what was the rationale for this change.

2020-08-27 10:42 UTC, t8m commented
Unfortunately I have no idea.

2020-08-27 10:48 UTC, ldv-alt commented
On Thu, Aug 27, 2020 at 03:42:21AM -0700, Tomáš Mráz wrote:
> Unfortunately I have no idea.

Should the issue be raised with those programs which introduced the problem in the first place?
After all, pam_wheel is not the only place in the system where getlogin could be used.
For me the suggestion to honor PAM_RUSER in pam_wheel looks like a way to mitigate a bug introduced in other software.

2020-08-27 12:32 UTC, t8m commented
The thing is nowhere in the pam_wheel documentation we say that the getlogin is the source of the information on who is the requesting user. Also the use_uid option documentation seems to be fairly misleading. So yes, alternatively (or in addition) we should fix the documentation.

2020-09-07 13:00 UTC, t8m commented
It might be that the programs that introduced the change should be reverted to original behavior. On the other hand I do not see a reason why this should not be merged. @ldv-alt do you have any strong reason why this should not be merged?

2020-09-07 14:45 UTC, ldv-alt commented
On Mon, Sep 07, 2020 at 06:01:08AM -0700, Tomáš Mráz wrote:
> It might be that the programs that introduced the change should be reverted to original behavior. On the other hand I do not see a reason why this should not be merged. @ldv-alt do you have any strong reason why this should not be merged?

I think we should promote use_uid option instead, but no, this is not a sustained objection.  If this fallback is to be merged, please make sure PAM_RUSER is not trusted when PAM_RHOST is also set.

2020-09-09 08:41 UTC, ikerexxe commented
I've made two changes taking into account your comments. The first on is that if PAM_RHOST is set, then PAM_RUSER is not used to identify the user. The second one consists in updating the man page to show the actual behaviour of use_uid option.

2020-09-09 08:52 UTC, t8m approved these changes
LGTM

2020-09-09 09:03 UTC, ldv-alt requested changes

2020-09-09 09:03 UTC, ldv-alt commented on modules/pam_wheel/pam_wheel.c
> +        }
Please check retval. 
Also, the scope of rhostname variable could be narrower than the whole function.

2020-09-09 20:26 UTC, ldv-alt approved these changes

2020-09-10 07:06 UTC, t8m commented
My approval holds as well.

2020-09-10 07:06 UTC, merged