pam_securetty: don't complain about missing config
linux-pam/linux-pam pull request #328
Opened 2021-01-26 13:00 UTC by lnussel

Not shipping a config file should be perfectly valid for distros while
still having eg login pre-configured to honor securetty when present.
PAM itself doesn't ship any template either. So avoid spamming the log
file if /etc/securetty wasn't found.

2021-01-26 13:07 UTC, t8m requested changes
Could you please keep the message conditional on `if (ctrl & PAM_DEBUG_ARG)` possibly with downgrading the priority to LOG_DEBUG?

2021-01-26 14:57 UTC, lnussel commented
Ah, right. Makes sense. Will do!

2021-01-26 17:19 UTC, t8m approved these changes

2021-01-26 20:36 UTC, ldv-alt approved these changes

2021-01-27 07:34 UTC, merged

2021-01-27 07:35 UTC, t8m commented
Merged. Thank you for the contribution!

2021-04-06 10:17 UTC, zeha commented
#158 was an earlier variant of this, which got shot down. Are the original arguments still valid or not?

2021-04-06 13:06 UTC, t8m commented
IMO the old behavior of returning success but logging an error is weird. That helps nobody. Also sometimes it is better to not manipulate the pam.d stacks if you have some preconfigured with a distro or a package. So yeah, you could remove pam_securetty from preconfigured configs to silence the syslog warnings but I do not think we should encourage innocent sysadmins doing that.

Also this change still allows for debugging messages by the debug argument.