module/pam_time: Fixed compile error for clang compiler
linux-pam/linux-pam pull request #442
Opened 2022-02-17 08:50 UTC by schubi2

Fixed error: Result of comparison against a string literal is unspecified (use an explicit string comparison function instead)

pam_time.c: Taking strcmp instead of comparing pointer.

2022-02-17 09:31 UTC, t8m approved these changes

2022-02-17 09:33 UTC, t8m commented on modules/pam_time/pam_time.c
> +    if (strcmp(*conffile, PAM_TIME_CONF) == 0) {
Another option would be to make the default value to be an static const char default_conf[] = PAM_TIME_CONF; And then you can keep using the pointer comparison.

2022-02-17 10:03 UTC, ldv-alt requested changes
Comparing pointers is a perfectly valid operation.
Comparing strings, on the other hand, would change `conffile=` semantics.
I'd suggest to initialize `*conffile` with `NULL` instead of `PAM_TIME_CONF`.

2022-02-18 16:06 UTC, schubi2 commented
> Comparing pointers is a perfectly valid operation. Comparing strings, on the other hand, would change `conffile=` semantics. I'd suggest to initialize `*conffile` with `NULL` instead of `PAM_TIME_CONF`.

Yes, good idea !

2022-02-21 11:48 UTC, thkukuk approved these changes

2022-02-21 12:08 UTC, ldv-alt commented
The patch itself is fine.
Could you cite the text printed by the compiler in the commit message, please?
Also please wrap long lines in commit messages, too.
I suppose it's a warning upgraded to error by -Werror.
If that's the case, then the commit message should say `fix clang compilation warning`
rather than the current `Fixed compile error of clang.`

2022-02-21 14:35 UTC, schubi2 commented
> The patch itself is fine. Could you cite the text printed by the compiler in the commit message, please? Also please wrap long lines in commit messages, too. I suppose it's a warning upgraded to error by -Werror. If that's the case, then the commit message should say `fix clang compilation warning` rather than the current `Fixed compile error of clang.`

Thanks. I have changed it.

2022-02-21 15:01 UTC, ldv-alt approved these changes

2022-02-21 22:52 UTC, merged