pam_pwhistory: load config from file
linux-pam/linux-pam pull request #473
Opened 2022-07-08 13:57 UTC by ikerexxe

I have modified the `read_config_file()` function provided in `pam_faillock` and added it to `pam_modutil`. This way libpam  provides a generic way of reading and parsing the `key-value` pairs defined in the configuration files.

Besides, I have added a new `conf` option in pam_pwhistory to select the configuration file to read. The default one being `/etc/security/pwhistory.conf`. On top of that I have used the newly created libpam function to read the pwhistory configuration file. This configuration is then loaded in the corresponding `options` structure.

Finally, I have documented the new `conf` option and the configuration file itself.

Please, review the libpam changes with care, as this is the first time that I change this library and I may have forgotten something.

Resolves: https://bugzilla.redhat.com/show_bug.cgi?id=2068461

2022-07-08 14:36 UTC, thkukuk commented
With pam_modutil_search_key we have already something similar...
Instead of re-inventing the wheel again and again, why not using one library doing the job? Especially as the new code is really unflexible. More and more projects allow to split config files in smaller parts or allow to override single values, so that you can separate between the vendor provided configuration file and the single changes the admin made. And since we have that for PAM already in many places, why should we introduce something again, which does not support this?
I'm strongly against adding something which limits us again.

We have code to use libeconf for reading login.defs, we have code using libeconf to read other configuration files, maybe it's time to consolidate on one best practices and one tool?

2022-07-08 15:39 UTC, thkukuk commented
Or in other words: are we 100% sure that we can use this generic parser for all current modules without the need to introduce another interface or another variant?
From my experience with this topic from libeconf, I heavily doubt that.

2022-07-11 08:53 UTC, ikerexxe commented
> With pam_modutil_search_key we have already something similar... Instead of re-inventing the wheel again and again, why not using one library doing the job?

You are absolutely right. I should have checked the existing APIs with more care before implementing a new one. Thanks for pointing me in the right direction @thkukuk.

I have updated the PR to use `pam_modutil_search_key()` and it's ready for review.

2022-07-11 09:34 UTC, thkukuk commented
Thanks. Looks good to me.

2022-07-11 13:25 UTC, ldv-alt requested changes
From a cursory look, there are just a few very minor issues.

2022-07-11 13:25 UTC, ldv-alt commented on libpam/include/security/pam_modutil.h
> + * @return value, or NULL if key was not found.
I suggest adding some English grammar to this description, e.g.
`for the key in the file` and `a similar`.

2022-07-11 13:25 UTC, ldv-alt commented on modules/pam_pwhistory/pwhistory_config.h
> +#endif /* _PWHISTORY_CONFIG_H */
No newline at end of file.

2022-07-12 07:25 UTC, ikerexxe commented
I fixed those issues and the PR is ready for review again.

2022-07-16 07:11 UTC, merged