pam_listfile: fix bad pointer
linux-pam/linux-pam pull request #511
Opened 2022-11-23 14:25 UTC by fayak

pam module listfile assume the group being tested will be written at the end of the argument list by carrying only a pointer to the value being examined in `myval` to `apply_val`

Therefore example
```auth    required       pam_listfile.so \
        onerr=succeed apply=ftp item=user sense=deny file=/etc/ftpusers```

modified from https://linux.die.net/man/8/pam_listfile is not working because `apply_val` will point to the latest value of `myval` which in this case will be `/etc/ftpusers` instead of `ftp`

This PR fixes this issue by copying the value of `myval` to `apply_val` instead of just taking a reference pointer

2023-01-14 12:48 UTC, ldv-alt requested changes
I agree with your analysis of the bug.
I wouldn't call it a `bad pointer`, though: there is nothing wrong with the pointer itself,
it's rather data clobbering or or data corruption or something like that.

Could you copy your description from the PR to the commit message itself, please?

2023-01-14 12:48 UTC, ldv-alt commented on modules/pam_listfile/pam_listfile.c
> +    memset(apply_val,'\0',sizeof(apply_val));
Looks like zeroing out the whole `apply_val` buffer is superfluous, `apply_val[0] = '\0'` should be sufficient.

2023-01-18 11:05 UTC, fayak commented
I've rephrased the title of the commit/PR, and added the description to the commit. Is it ok for you ?

2023-01-18 15:31 UTC, ldv-alt approved these changes

2023-01-18 16:24 UTC, merged