libpam: pam_tty_audit error due to buffer size limit
linux-pam/linux-pam pull request #561
Opened 2023-04-13 07:05 UTC by DeepakDas7

Resolves EACCES error due to 1024 buffer size while reading individual lines in pam files.

Resolves: https://github.com/linux-pam/linux-pam/issues/532

2023-04-28 13:34 UTC, ldv-alt commented
This just raises the line buffer size limit from 1024 to 8192.

2023-09-12 05:34 UTC, DDDas7 commented
Hi  Dimitry ( @ldv-alt ) ,

Greetings!

I have added a new patch. Can you please review the updated  patch .

Thank you!

Regards,
Deepak

2023-10-05 10:20 UTC, ldv-alt requested changes
I suggest changing `_pam_assemble_line` instead, for example, by using `getline` instead of `fgets` there.

2023-10-05 10:20 UTC, ldv-alt commented on libpam/pam_handlers.c
> +#define BUF_SIZE                  4096
Since you're introducing a dynamic memory allocation, what's the reason of changing default?

2023-10-05 10:20 UTC, ldv-alt commented on libpam/pam_handlers.c
> +    char *buf = (char *) malloc(BUF_SIZE * sizeof(char));
malloc return values do not require a cast.

2023-10-05 10:20 UTC, ldv-alt commented on libpam/pam_handlers.c
> +	    buf = (char *) realloc(buf, mod_buf_size * sizeof(char));
This introduces a memory leak on error path.

2023-10-05 10:20 UTC, ldv-alt commented on libpam/pam_handlers.c
> +                return PAM_ABORT;
This should rather return `PAM_BUF_ERR`, see examples in this file.

2023-10-05 10:20 UTC, ldv-alt commented on libpam/pam_handlers.c
> +	    memset(buf, '\0', mod_buf_size * sizeof(char));
Why `memset` is needed here?

2023-10-05 10:20 UTC, ldv-alt commented on libpam/pam_handlers.c
> +            fseek(f, file_pos, SEEK_SET);
Sorry, but this is not acceptable, there shouldn't be any re-reading of the file.

2023-11-29 11:39 UTC, DDDas7 commented
Hi Dimitry ( @ldv-alt ) ,

Greetings!

I have added a new patch. Can you please review the updated patch .

Thank you!

Regards,
Deepak

2023-11-29 14:07 UTC, DDDas7 commented
Hi Dimitry ( @ldv-alt ) ,

Greetings!

I have added a new patch and committed the change..  Some tests are failing during checks. I am presently reviewing it and will update once the issue is fixed.

Thank you!

2023-12-01 09:16 UTC, BenBE commented on libpam/pam_handlers.c
> +        free(buf);
`free(NULL);` is a no-op on any non-broken C library implementation.
– C99 standard, section 7.20.3.2/2

2023-12-04 23:01 UTC, stoeckmann commented on libpam/pam_handlers.c
> +		free(*buffer);
This leads to a double free when the while-loop in _pam_parse_conf_file is left. The free is performed after the while as well.

2023-12-04 23:05 UTC, stoeckmann commented
Also I'm not entirely sure if the code base is ready for arbitrarily long lines as it is right now. There are some cases where strlen's return value is stored in int, which would overflow with 2 GB lines.

I'm well aware that it's very very unlikely to encounter such lines, but to me it seems that not that many persons had problems with the 1024 character limit so far either.

2023-12-12 12:13 UTC, stoeckmann commented
Please see https://github.com/linux-pam/linux-pam/pull/658 for my attempt of solving it. It also fixes some issues with current configuration parsing.

2024-01-01 17:14 UTC, closed without merging