pam_xauth: switch away from PATH_MAX
linux-pam/linux-pam pull request #579
Opened 2023-05-15 01:59 UTC by pinotree

Allocate the path buffer in `check_acl()` dynamically using `asprintf()`, so there is no need to use a PATH_MAX-fixed size buffer. The fallback PATH_MAX definition is no more needed, thus is dropped.

2023-05-15 02:06 UTC, pinotree commented
Note there is a potential behaviour change: in case the resulting `path` is longer than `PATH_MAX`, or in general too long to cause `stat()` to fail with `ENAMETOOLONG`, the return value of `check_acl()` changes from `PAM_SESSION_ERR` (because of the former `i >= (int)sizeof(path)` check) to `PAM_PERM_DENIED` (because of the error handling block at the end of the function).

In case the previous return value is needed, I can add an additional error handling block for `ENAMETOOLONG`.

2023-05-16 21:00 UTC, ldv-alt commented
Yes, according to the documentation, the return value has to be `PAM_SESSION_ERR` in case of `ENAMETOOLONG`.

2023-05-17 19:15 UTC, pinotree commented
> Yes, according to the documentation, the return value has to be `PAM_SESSION_ERR` in case of `ENAMETOOLONG`.

Thanks! Fixed accordingly.

2023-05-17 20:05 UTC, ldv-alt requested changes

2023-05-17 20:05 UTC, ldv-alt commented on modules/pam_xauth/pam_xauth.c
> +				   "too long path: %s", path);
Let's use the same wording as in the default case:
```
pam_syslog(pamh, LOG_ERR, "error opening %s: %m", path);
```

2023-05-17 22:29 UTC, ldv-alt approved these changes

2023-05-17 22:35 UTC, merged