doc: Fix uses of not neutral pronouns
linux-pam/linux-pam pull request #745
Opened 2024-01-19 15:49 UTC by AuraHerreroRuiz

There are some cases where the documentation or code comments use non-neutral pronouns. This PR changes these to use neutral pronouns to match the rest of the documentation.

2024-04-01 19:40 UTC, ldv-alt requested changes
I'm sorry but they/their is harder to read when applied to singular forms.  Fortunately, you can easily achieve the goal by tweaking these phrases, e.g. to use plural forms instead of singular.

2024-04-02 12:46 UTC, ldv-alt requested changes

2024-04-02 12:46 UTC, ldv-alt commented on doc/sag/Linux-PAM_SAG.xml
> +      can configure their favorite ``Shoot 'em up game'' (PAM-aware of course) to
I suggest the following wording:
```
situation: system administrators (parents) wish to improve the
mathematical ability of their users (children). Their favorite
``Shoot 'em up game'' (PAM-aware of course) can be configured to
```

2024-04-02 12:46 UTC, ldv-alt commented on doc/specs/rfc86.0.txt
> +            given access to their respective accounts.  This function can implement
I suggest the following wording:

```
function to check whether the authenticated user should be
...
given access to the account.  This function can implement
```

2024-04-02 12:46 UTC, ldv-alt commented on libpam/pam_audit.c
> +  /* libaudit sets errno to the user's own negative error code. This can be
The comment is talking about libaudit's own error code, so this edit changes the meaning.
I suggest the following wording:
`libaudit sets errno to its own negative error code.`

2024-04-02 12:46 UTC, ldv-alt commented on modules/pam_env/pam_env.conf.5.xml
> +      for the users' respective <emphasis>passwd</emphasis> entries.
I suggest the following wording:
`for the user from the corresponding <emphasis>passwd</emphasis> entry.`

2024-04-02 12:46 UTC, ldv-alt commented on modules/pam_timestamp/pam_timestamp_check.8.xml
> +               users authenticate as themselves. When users authenticate as a
I suggest the following wording:
`users authenticate as themselves. When the user authenticates as a`

2024-04-02 13:32 UTC, AuraHerreroRuiz commented
I've committed your suggestions, let me know if you need further changes

2024-04-02 14:07 UTC, ldv-alt approved these changes
Looks fine now.  I've rebased and squashed the commits.

2024-04-03 09:57 UTC, merged