Support elogind as logind alternative
linux-pam/linux-pam pull request #787
Opened 2024-04-11 05:36 UTC by Polynomial-C

Can be enabled with --enable-logind=elogind

logind from systemd is still the default

2024-04-11 05:46 UTC, Polynomial-C commented
You can find the elogind project here: https://github.com/elogind/elogind

It's a drop-in replacement for systemd-logind as it's based on the systemd sources.

2024-04-11 08:15 UTC, thkukuk commented
Basically the patch is ok, but I expect that Linux-PAM will use more systemd functions in the future, even if I don't have anything concrete in mind at the moment.

That's why I would prefer SYSTEMD_LIBS and EGLOGIND_LIBS to be two independent variables from the beginning, so that we don't have to separate them later again.

@ldv-alt what do you think?

2024-04-11 11:31 UTC, ldv-alt requested changes

2024-04-11 11:31 UTC, ldv-alt commented on configure.ac
> +  AS_CASE(["$enableval"], [elogind], [
Wouldn't it be better to use `AS_CASE(["$WITH_LOGIND"], ...)` instead of `AS_IF(...)` and `AS_CASE(["$enableval"], ...)`?

2024-04-11 11:31 UTC, ldv-alt commented on configure.ac
> +    PKG_CHECK_MODULES([LOGIND], [libsystemd >= 254], [LOGIND_CFLAGS="-DUSE_LOGIND=1 $LOGIND_CFLAGS"], [AS_IF([test "$WITH_LOGIND" != "check"], [AC_MSG_ERROR([Cannot find libsystemd])])])
When using `AS_CASE`, it would be more readable to handle each case separately rather than  merging `yes` and `check` cases.

2024-04-11 11:38 UTC, ldv-alt commented
> Basically the patch is ok, but I expect that Linux-PAM will use more systemd functions in the future, even if I don't have anything concrete in mind at the moment.
> 
> That's why I would prefer SYSTEMD_LIBS and EGLOGIND_LIBS to be two independent variables from the beginning, so that we don't have to separate them later again.
> 
> @ldv-alt what do you think?

We could have SYSTEMD_* and ELOGIND_* variables initialized in configure.ac, and LOGIND_* variables based on them that are AC_SUBST'ed and would currently be used in Makefile.am files.  This way we could make SYSTEMD_* variables AC_SUBST'ed when needed.

2024-04-17 08:49 UTC, thkukuk commented
> However, why would PAM use (any) systemd (functions), as systemd-logind uses PAM, and has several PAM modules. One of them, pam_systemd, is distributed as pam_elogind by us.

If PAM would not use systemd functions, there would be no need for you to add elogind support.
One year ago PAM didn't used any libsystemd function and nobody could imagine that we ever would. Now we are using libsystemd functions to replace `utmp` with systemd-logind. 
Nobody knows what will come tomorrow, and which functions more we need/want to use.

2024-11-26 17:18 UTC, closed without merging

2024-11-26 17:18 UTC, ldv-alt commented
Superseded by #859.