pam_set_item: disallow setting service to NULL
linux-pam/linux-pam pull request #803
Opened 2024-05-30 11:32 UTC by Blarse

This also prevents a possible segfault when pam_set_item tries to convert an empty service_name to lower case.

2024-06-23 17:14 UTC, ldv-alt requested changes
Looks good, thanks.
Please add your comment from the PR to the commit message itself.

2024-06-23 17:14 UTC, ldv-alt commented on libpam/pam_item.c
>  	/* Setting handlers_loaded to 0 will cause the handlers
Given that without this change pam_set_item(pamh, PAM_SERVICE, NULL) just segfaults, and pam_start doesn't allow NULL service name, setting service to NULL is essentially not allowed anyway, so I think it's safe to apply this change.

With regards to the return value, PAM_BAD_ITEM is probably OK: it's the closest error code among those that are listed in the documentation for pam_set_item.  Apparently, pam_set_item(pamh, PAM_CONV, NULL) returns PAM_PERM_DENIED, but this is not documented.

2024-06-24 07:59 UTC, Blarse commented
> Please add your comment from the PR to the commit message itself.

I think this has already been done, if I understood you correctly.

2024-06-24 08:42 UTC, ldv-alt approved these changes

2024-06-24 13:39 UTC, merged